- hosts: all
  tasks:

    - name: Create Docker Network
      ansible.builtin.docker_network:
        name: NetAutomation

    - name: Ensure Jenkins directory on host
      file:
        state: directory
        owner: 1000
        group: 1000
        path: /share/jenkins
      become: yes

    - name: Ensure Jenkins Agent directory on host
      file:
        state: directory
        owner: 1000
        group: 1000
        path: /share/jenkins_agent1
      become: yes

    - name: Create Jenkins Container
      docker_container:
        name: jenkins
        hostname: jenkins.mylab.com
        image: jenkins/jenkins:latest
        networks:
          - name: NetAutomation
            aliases:
              - jenkins_net
        published_ports:
          - 8080:8080
          - 50000:50000
        volumes:
          - /share/jenkins:/var/jenkins_home
        state: started
        recreate: no
      become: yes

    - name: Create Jenkins Agent Container
      docker_container:
        name: jenkins-agent1
        hostname: jenkins-agent1.mylab.com
        image: jenkins-agent
        networks:
          - name: NetAutomation
            aliases:
              - jenkins_net
        published_ports:
          - "2022:22"
        volumes:
          - /share/jenkins_agent1:/home/jenkins
        state: started
        recreate: no
      become: yes
